version: '3'
services:
  websocket-server:
    container_name: websocket-server
    build:
      context: .
    restart: always
    environment:
      - REMOTE_SERVER_AUTH=${REMOTE_SERVER_AUTH}
  websocket-nginx:
    container_name: websocket-nginx
    image: nginx:1.27
    restart: always
    environment:
      ENVSUBST_VARS: NGINX_HOST
      NGINX_HOST: ${REMOTE_SERVER_DOMAIN}
    ports:
      - ${REMOTE_SERVER_PORT}:443
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf/templates:/etc/nginx/templates
      - ./nginx-conf/custom-entrypoint.sh:/custom-entrypoint.sh
    entrypoint: ["chmod +x /custom-entrypoint.sh && /custom-entrypoint.sh"]